\documentclass[a4paper,14pt]{article}
\usepackage[paperwidth=21cm,paperheight=29.7cm,top=3cm,right=1.5cm,bottom=3cm,left=1.5cm]{geometry}
\usepackage{makeidx}
%\usepackage{CJKutf8}
%\usepackage{xeCJK}
%\usepackage{multirow}
%\usepackage{multicol}
%\usepackage[dvipsnames,svgnames,table]{xcolor}
\usepackage{graphicx}
\usepackage{epstopdf}
\usepackage{ulem}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{fontspec}
\usepackage[toc,page]{appendix}
\usepackage{pdflscape}
\usepackage{supertabular}
\usepackage{dcolumn}
%\setCJKmainfont{標楷體}
\author{Oscar Deng}
\title{企業競爭策略與產業競爭程度對避稅行為之影響}
\date{\today}
\begin{document}
%\begin{CJK}{UTF8}{kaiu}
\tableofcontents
\maketitle
\appendix
\section{\\Appendix A: Preparing everything} \label{App:Appendix A}
<<label="settings", results='hide'>>=
#source("setSweave.R")
#source("setSweave.big5.R")
require(stargazer)
require(xtable)
require(dplyr)
require(data.table)
require(ggplot2)
require(stats)
source("corstars.R")
TEJ8.1 <- read.csv("TEJ8.1.csv",row.names = 1)
@

\newpage
\section{\\Appendix D.1: Descriptive Statistics Table} \label{App:Appendix D.1}
<<label="descriptive stat tab", results='asis'>>=
stargazer(
    TEJ8.1 %>% select(ETR,CETR,STR,HHI_Dum,STR_HHI,ROA,SIZE,LEV,
                      INTANG,QUICK,EQINC,OUTINSTI,RELAT,FAM_Dum,GDP,
                      #,RD,EMP,MB,MARKET,PPE
                      STR_RD,STR_EMP,STR_MB,STR_MARKET,STR_PPE
                      )
 ,type = "latex"
 ,summary.stat = c("n","min","p25","median","p75","max","sd","mean")
 ,table.placement = "h!"
 ,title = "Descriptive Statistics Table"
 ,notes.append = TRUE)
@
\newpage

\section{\\Appendix D.1.1: figures of each variables} \label{App:Appendix D.1.1}
ETR與CETR分布圖(winsor前後)\\
  <<results='asis'>>=
qplot(ETR,CETR,data=TEJ8.1);qplot(ETR,CETR,data=TEJ8.1)
@

\newpage
\section{\\Appendix D.2: Table of Market Structure(HHI)} \label{App:Appendix D.2}
<<results='markup'>>=
plottbA5 <- function(x=TEJ8.1){
  x$TSE <- paste(x$TSE_code,x$TSE_name,sep="")
  HHI_DB <- base::subset(x, select=c(TSE,year,HHI)) %>% distinct
  HHI_DB$HHI <- replace(HHI_DB$HHI,HHI_DB$HHI >= 0.3,'高寡佔I 型')
  HHI_DB$HHI <- replace(HHI_DB$HHI,HHI_DB$HHI < 0.3 & HHI_DB$HHI >= 0.18,'高寡佔II 型')
  HHI_DB$HHI <- replace(HHI_DB$HHI,HHI_DB$HHI < 0.18 & HHI_DB$HHI >= 0.14,'低寡占I 型')
  HHI_DB$HHI <- replace(HHI_DB$HHI,HHI_DB$HHI < 0.14 & HHI_DB$HHI >= 0.1,'低寡占II 型')
  HHI_DB$HHI <- replace(HHI_DB$HHI,HHI_DB$HHI < 0.1 & HHI_DB$HHI >= 0.05,'競爭I 型')
  HHI_DB$HHI <- replace(HHI_DB$HHI,HHI_DB$HHI < 0.05,'競爭II 型')
  HHI_DB$HHI <- replace(HHI_DB$HHI,HHI_DB$HHI == "NaN","")
  HHI_tbl <- dcast(HHI_DB,TSE ~ year) %>% as.data.frame
  HHI_tbl <- as.data.frame(HHI_tbl[,-1],row.names=HHI_tbl[,1])
  return(HHI_tbl)
  };HHI_tbl <- plottbA5()
@


\end{document}
