---
output: html_document
---

報表輸出
=============================
```{r requireNload, include=FALSE}
require(readxl)
require(xlsx)
require(plyr)
require(dplyr)
require(knitr)
require(data.table)
require(grid)
require(gridExtra)
require(ggplot2)
require(zoo)
require(R.oo)
require(R.utils)
require(psych)
require(robustHD)
require(rbenchmark)
require(foreign)
require(rgl)
require(stargazer)
require(rmarkdown)
require(taRifx)
require(kable)
require(xtable)
TEJ <- read.csv("D:\\Documents\\Dropbox\\MyEssay\\Rcoding\\TEJout.csv", row.names = 1, sep=",", header = TRUE)
TEJ101 <- read.csv("D:\\Documents\\Dropbox\\MyEssay\\Rcoding\\TEJ101out.csv", row.names = 1, sep=",", header = TRUE)
TEJ01 <- read.csv("D:\\Documents\\Dropbox\\MyEssay\\Rcoding\\TEJ01out.csv", row.names = 1, sep=",", header = TRUE)
```

表一、樣本篩選表
=============================
```{r table1, results='asis'}
  x <- nrow(TEJ)
  x1 <- nrow(TEJ[TEJ$TSE_code=='M2800',])
  x2 <- nrow(TEJ[TEJ$TSE_code=='M9900',])
  x3 <- nrow(TEJ[TEJ$TSE_code=='M2331',])
  x4 <- nrow(TEJ[TEJ$TSE_code=='W91',])
  DB05 <- TEJ[!(TEJ$TSE_code %in% c('M2800','M9900','M2331','W91')),]
  x5 <- nrow(DB05)
  DB06 <- as.data.table(DB05)[,.SD[.N<5],by=list(TSE_code,year(date))]
  x6 <- nrow(DB06)
  DB07 <- as.data.table(DB05)[,.SD[.N >= 5],by=list(TSE_code,year(date))]
  x7 <- nrow(DB07)
  DB08 <- DB07[(DB07$FAMILY %in% NA) |(DB07$PB %in% NA) |(DB07$TA %in% NA) |(DB07$NetSales %in% c(0,NA)) |(DB07$employee %in% NA)]
  x8 <- nrow(DB08)
  DB09 <- DB07[!(DB07$FAMILY %in% NA) & !(DB07$PB %in% NA) & !(DB07$TA %in% NA) & !(DB07$NetSales %in% c(0,NA)) & !(DB07$employee %in% NA)]
  x9 <- nrow(DB09)
  tbA1 <- data.frame(
  '說明'= c('2001~2015 原始樣本總數','刪除金融保險業(TSE產業代碼 M2800)','刪除其他產業(TSE產業代碼 M9900)',
          '刪除其他電子業(TSE產業代碼 M2331)','刪除存託憑證(TSE產業代碼 W91)','刪除當年度產業內公司家數不足5筆之樣本',
          '刪除有缺漏值且足以影響分析之樣本','全樣本合計'),
  '樣本數'=as.integer(c(x, x1, x2, x3, x4, x6, x8, x9)),
  '小計'=as.integer(c(x,'','','',ifelse(x1+x2+x3+x4 == x-x5,x-x5,'error'),'',x6+x8,ifelse(x5-x6-x8 == x9,x9,'error')))
  )
  
  theme1 <- ttheme_default(
    core = list(
      fg_params = list(
        fontface=c(rep("plain", 7),"bold.italic")
        #fontsize,hjust=0,x=0.1
        ),
      bg_params = list(
        fill=c(rep(c("grey95", "grey90"),length.out=7),"#6BAED6"),
        alpha = rep(c(1,0.5), each=5)
        )
      ),
    colhead = list(
      fg_params = list(fontsize=9,fontface="bold"))
  )
  
  m <- format(tbA1, digits = 1, scientific=F,big.mark = ",")
  g1 <- tableGrob(m, theme = theme1, rows=NULL)
  grid.draw(g1)

```

表二、產業年份分配表
=============================
```{r table2, results='asis'}
  TEJ01$TSE <- paste(TEJ01$TSE_code,TEJ01$TSE_name,sep=" ")
  tbA2 <- as.data.frame.matrix(table(TEJ01$TSE,TEJ01$year))
  tbA2 <- rbind(tbA2, '總計'=as.numeric(colSums(tbA2)))
  tbA2 <- cbind(tbA2, '合計'=rowSums(tbA2))
  #'kable(tbA2,format = "html")
  stargazer(tbA2,type="html",title="表二、產業年份分配表",summary = FALSE,column.labels=c("年分"),column.separate=c(16))
  
  
  xtable(tbA2)
```

表三、各變數之敘述統計量
=============================
```{r table3,results='asis'}
TEJ <- read.csv("TEJ101out.csv",sep=",",row.names = 1,header = TRUE)
output <- TEJ[,6:21]
stargazer(output,type = "html",title="表三、各變數之敘述統計量",mean.sd = TRUE, median = TRUE,iqr=TRUE,min.max=TRUE,column.labels=c("統計量","樣本個數","平均數","標準差","最小值","最大值"),column.separate=c(1,1,1,1,1,1)) -> star
```



